DIRECCIONES = [":front", ":right", ":left", ":back"]
ORIENTACIONES = [":north", ":south", ":west", ":east"]
ROTACIONES = [":left", ":right", ":around"]
CONSTANTES = ["Dim", "myXpos", "myYpos", "MyChips", "myBalloons", "balloonsHere", "ChipsHere", "Spaces"]
OBJETOS = [":balloons", ":chips"]